# dataset general info
flow_path: youtubevos_flows
frame_path: youtubevos_frames
name2len: config/youtubevos_name2len.pkl

flow:
  flow_height: 256
  flow_width: 256
  augments: False
  colors: RGB
  ext: .jpg

edge:
  sigma: 1
  low_threshold: 0.1
  high_threshold: 0.2
