PASSMASK: 1
alpha: 0.3
ape: 1
cnum: 64
conv_type: vanilla
dist_cnum: 32
drop: 0
frame_hidden: 512
gd: 4
in_channel: 4
init_weights: 1
input_resolution: !!python/tuple
- 240
- 432
flow_inChannel: 2
flow_cnum: 64
flow_hidden: 256
kernel_size: !!python/tuple
- 7
- 7
mlp_ratio: 40
numBlocks: 8
num_head: 4
padding: !!python/tuple
- 3
- 3
stride: !!python/tuple
- 3
- 3
sw: 8
tw: 2
use_bias: 1
norm: None
model: model